### ISSUE TITLE
Perfect Vision throws error v 3.0.4 F 09 tester 2

### ISSUE THREAD

**Issue by Battenhatch** [dev7355608/perfect-vision#155]
After updating to 3.0.4 I get this message in the console:
foundry.js:326 TypeError: g.clear is not a function
[Detected 3 packages: betterroofs, lib-wrapper, perfect-vision]
    at ForegroundLayer._drawOcclusionShapes (foundry.js:29160)
    at ForegroundLayer.updateOcclusion (foundry.js:29144)
    at Z.🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:502)
    at ForegroundLayer.occlusionLink (occlusionlink.js:32)
    at Z.🎁call_wrapper [as call_wrapper] (libWrapper-wrapper.js:611)
    at ForegroundLayer.🎁ForegroundLayer.prototype.updateOcclusion#0 (libWrapper-wrapper.js:184)
    at PerceptionManager._update (foundry.js:32453)
    at PerceptionManager.update (foundry.js:32376)
    at PerceptionManager.initialize (foundry.js:32385)
    at Canvas._initialize (foundry.js:19537)
    at async Canvas.draw (foundry.js:19424)
    at async Canvas.🎁Canvas.prototype.draw#perfect-vision (canvas.js:345)
    at async Scene.view (foundry.js:17216)
    at async Game.initializeCanvas (foundry.js:5476)
    at async Game.setupGame (foundry.js:5349)
    at async Game._initializeGameView (foundry.js:6287)
    at async Game.initialize (foundry.js:5245)

**Comment by dev7355608** [comment]
This error should be impossible. Could you check whether Better Roofs is up to date? Do you get libWrapper conflict errors as well? And try CTRL+F5.

**Comment by Battenhatch** [comment]
ctrl+F5 seems to have cleared it. Hadn't heard of that trick before :)
